export const FETCH_POSTS = "FETCH_POSTS"

export const FETCH_MESSAGE = "FETCH_MESSAGE"

export const FETCH_CONS = "FETCH_CONS" 

export const FETCH_SECONDUSER = "FETCH_SECONDUSER"

export const FETCHH_SECONDUSER = "FETCHH_SECONDUSER"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"


export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"

export const REGISTER_USER_FAIL = "FEREGISTER_USER_FAIL"


export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"

export const ADD_POSTS = "ADD_POSTS"

export const ADD_CON = "ADD_CON"

export const LOGOUT_USER = "LOGOUT_USER"

export const LOGOUT_SECONDUSER = "LOGOUT_SECONDUSER"

export const CLEAR_POSTS = "CLEAR_POSTS"

export const DELETE_CON = "DELETE_CON"

export const RENAME_USER = "RENAME_USER"
